tdt/product/urls.py
from django.urls import path, include, re_path
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from .views import *

app_name = 'product'
urlpatterns = [
    path('create/', ProductCreateView.as_view(), name='product_add'),
    path('list/', my_product_list, name='products_list'),
    path('update/<int:pk>', ProductUpdateView.as_view(), name='product_update'),
    path('delete/<int:pk>', ProductDeleteView.as_view(), name='product_delete'),

]

tdt/tdt/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls', namespace='authentication')),
    path('', include('emailconfig.urls', namespace='emailconfig')),
    path('product/', include('product.urls', namespace='products')),
    path('order/', include('order.urls', namespace='order')),
    path('', include('dashboard.urls', namespace='dashboard')),

    path('forgot/password/reset/', auth_views.PasswordResetView.as_view(template_name='registration/forgot_password.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/forgot_password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/forgot_password_reset.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name= 'registration/forgot_password_reset_complete.html'), name='password_reset_complete'),
    # path('', include('home.urls', namespace='home')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tdt/product/models.py
from django.db import models

from authentication.models import User


#product type
class Product_Type(models.Model):

    product_type_name = models.CharField(max_length=25,unique=True,null=False,blank=False)
    status = models.BooleanField(default=False)
    detail = models.CharField(max_length=250, blank=False)
    product_type_image = models.ImageField(
        null=True, blank=True, upload_to='images/product_type/')

    def __str__(self):
        return self.product_type_name

class Product(models.Model):
    product_name = models.CharField(max_length=50, blank=False)
    product_type = models.ForeignKey(
        Product_Type, on_delete=models.CASCADE, related_name='product_type')
    status = models.BooleanField(default=False)
    detail = models.CharField(max_length=250, blank=False)
    product_image = models.ImageField(
        null=True, blank=True, upload_to='images/product/')
    price = models.FloatField()
    quantity = models.IntegerField()
    users = models.ForeignKey(
        'authentication.User', on_delete=models.CASCADE, related_name='product_user')

    def __str__(self):
        return self.product_name

class ProductTransaction(models.Model):
    TRANSACTION_TYPE = (
        ('Personal_Consumption', 'Personal_Consumption'),
        ('Parent_Child', 'Parent_Child'),
        ('Bad_Debts','Bad_Debts')
    )
    seller = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='seller', blank= False)
    buyer = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='buyer', blank= False)
    transaction_type = models.CharField(
        max_length=100, choices=TRANSACTION_TYPE, default="Parent_Child")

    def __str__(self):
        return self.transaction_type
    

tdt/product/forms.py
from django import forms
from .models import Product

class ProductForm(forms.ModelForm):
    # username = forms.CharField(max_length=20, widget=forms.TextInput(
    #     attrs={'readonly': 'readonly'}))
    class Meta:
        model = Product
        fields = '__all__'
        # fields = ('username','product_name','product_type','status','detail','product_image','price','quantity')

tdt/product/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView,FormView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Product
from .forms import ProductForm
from authentication.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.template.loader import render_to_string




def my_product_list(request):
    products = Product.objects.filter(users=request.user)
    return render(request, 'product_list.html', {'products': products, })

class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    template_name = 'product_create.html'
    success_url = reverse_lazy('products:products_list')


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm
    template_name = 'product_create.html'
    success_url = reverse_lazy('products:products_list')


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    context_object_name = 'product'
    template_name = 'product_delete.html'
    success_url = reverse_lazy('products:products_list')



# class ProductCreateView(SuccessMessageMixin, FormView):
#     template_name = 'product_create.html'
#     initial = {}
#     form_class = ProductForm
#     success_url = '/thanks/'
#     success_message = 'success.'
#     data = dict()
#     def get(self, request, *args, **kwargs):
#         user_pk = request.user.pk
#         user1 = User.objects.get(pk = user_pk)
#         self.initial['username'] = user1
#         form = self.form_class(initial=self.initial)
#         self.data['html_form'] = render_to_string(self.template_name, {'form':form}, request=request)
#         return render(request, 'product_create.html', {'form': form})

#     def post(self, request, *args, **kwargs):
#         form = self.form_class(request.POST)
#         if form.is_valid():
#             instance = form.save(commit=False)
#             if  request.user.is_authenticated:
#                 instance.user  = request.user
#             instance.save()
#             self.data['form_is_valid']=True
#             return JsonResponse(self.data)
#         else:
#             self.data['form_is_valid']=False
#             self.data['html_form'] = render_to_string(self.template_name, {'form':form}, request=request)
#         return render(request, 'product_create.html', {'form': form})

tdt/product/templates/product_create.html
<!DOCTYPE html>
<html lang="en">

<body id="page-top">
    {% include 'head.html' %}
    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        {% include 'sidebar.html' %}
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                <!-- Topbar -->
                {% include 'navbar.html' %}
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                {% block content %}
                <form method="POST" enctype='multipart/form-data' action="">
                    {% csrf_token %}
                    <table>{{ form }}</table>
                    <input type="submit" value="Add Product" />
                </form>
                {% endblock %}
                <!-- /.container-fluid -->
            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <!-- End of Footer -->
        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    <!-- Bootstrap core JavaScript-->
    {% include 'javascript.html' %}
</body>

</html>

tdt/product/templates/product_delete.html
<!DOCTYPE html>
<html lang="en">

<body id="page-top">
    {% include 'head.html' %}
    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        {% include 'sidebar.html' %}
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                <!-- Topbar -->
                {% include 'navbar.html' %}
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                {% block content %}
                <form method="post">
                    {% csrf_token %}
                    <center>
                        <h3> Are you sure want to delete "{{ product }}"</h3>
                        <input type="submit" value="Confirm" class="btn btn-danger">
                </form>
                </p>
                </center>
                {% endblock %}
            </div>
        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    <!-- Bootstrap core JavaScript-->
    {% include 'javascript.html' %}
</body>

</html>

tdt/product/templates/product_list.html
<!DOCTYPE html>
<html lang="en">

<body id="page-top">
    {% include 'head.html' %}
    <!-- Page Wrapper -->
    <div id="wrapper">
        <!-- Sidebar -->
        {% include 'sidebar.html' %}
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">
            <!-- Main Content -->
            <div id="content">
                <!-- Topbar -->
                {% include 'navbar.html' %}
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                {% block content %}
                <div class="container-fluid">
                    <!-- Page Heading -->
                    <div class="d-sm-flex align-items-center justify-content-between mb-4">
                        <h1 class="h3 mb-0 text-gray-800">Product List</h1>
                        <a href="{% url 'product:product_add' %}" class="d-none d-sm-inline-block btn btn-sm btn-success shadow-sm">Add Product</a>
                    </div>
                    <!-- Content Row -->
                    <div class="row">
                        <!-- Earnings (Monthly) Card Example -->
                        <!-- Earnings (Monthly) Card Example -->
                        {% for product in products %}
                        <div class="card" style="width:25rem;margin-top:20px;margin-right:10px;">
                            {% if product.product_image %}
                            <img class="card-img-top" src="{{product.product_image.url}}" alt="Card image cap" height="250px" width="25px">
                            {% endif %}
                            <div class="card-body">
                                <h5 class="card-title">{{ product.product_name }}</h5>
                                <p class="card-text">{{product.detail}}</p>
                            </div>
                            <ul class="list-group list-group-flush">
                                <li class="list-group-item">Price: Rs.{{product.price}}</li>
                                <li class="list-group-item">Quantity: {{product.quantity}}</li>
                            </ul>
                             <div class="card-body">
                               <a href="{% url 'product:product_update' product.pk %}"><button type="button" class="btn btn-success">Update</button></a>
                              <a href="{% url 'product:product_delete' product.pk %}"><button type="button" class="btn btn-danger" style="float: right;">Delete</button></a>
                            </div>
                        </div>
                        {% endfor %}
                        <br><br><br>
                    </div>
                </div>
                {% endblock %}
            </div>
        </div>
        <!-- End of Content Wrapper -->
    </div>
    <!-- End of Page Wrapper -->
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>
    <!-- Bootstrap core JavaScript-->
    {% include 'javascript.html' %}
</body>

</html>