tdt/authentication/urls.py
from django.urls import path,include,re_path
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from authentication import views


app_name = 'authentication'
urlpatterns = [
	# path('signup/',(views.UserSignupForm.as_view()), name='signup'),
	path('admin/signup/',(views.AdminUserSignupForm.as_view()), name='admin_signup'),
	path('user/signup/',(views.NormalUserSignupForm.as_view()), name='user_signup'),
	path('logout/', views.logout_view, name='logout'),
	path('login/', (auth_views.LoginView.as_view(template_name='index.html')), name='login'),
	]

tdt/emailconfig/urls.py
from django.urls import path,include,re_path
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from emailconfig import views


app_name = 'emailconfig'
urlpatterns = [
	path('user/fetch/parent/',(views.FetchParentView.as_view()), name='fetchparent'),
	

	]

tdt/tdt/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls', namespace='authentication')),
    path('', include('emailconfig.urls', namespace='emailconfig')),
    path('product/', include('product.urls', namespace='products')),
    path('order/', include('order.urls', namespace='order')),
    path('', include('dashboard.urls', namespace='dashboard')),

    path('forgot/password/reset/', auth_views.PasswordResetView.as_view(template_name='registration/forgot_password.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/forgot_password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/forgot_password_reset.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name= 'registration/forgot_password_reset_complete.html'), name='password_reset_complete'),
    # path('', include('home.urls', namespace='home')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tdt/emailconfig/models.py
from django.db import models
from authentication.models import User


class FetchParentRequest(models.Model):
    parent_email = models.EmailField()
    approved = models.BooleanField(default=False)
    your_email = models.EmailField()
    
    def __str__(self):
    	return 'Request Email-{}'.format(self.your_email)

tdt/emailconfig/forms.py
from django import forms
from authentication.models import User,AdminUser,NormalUser
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
from tdt.settings import ALLOWED_SIGNUP_DOMAINS
from .models import FetchParentRequest

def SignupDomainValidator(value):
    if '*' not in ALLOWED_SIGNUP_DOMAINS:
        try:
            domain = value[value.index("@"):]
            if domain not in ALLOWED_SIGNUP_DOMAINS:
                raise ValidationError('Invalid domain. Allowed domains on this network: {0}'.format(','.join(ALLOWED_SIGNUP_DOMAINS)))  # noqa: E501

        except Exception:
            raise ValidationError('Invalid domain. Allowed domains on this network: {0}'.format(','.join(ALLOWED_SIGNUP_DOMAINS)))  # noqa: E501


def UniqueEmailValidator(value):
    if User.objects.filter(email__iexact=value).exists():
        raise ValidationError('User with this Email already exists.')

def ParentEmailValidator(value):
    if User.objects.filter(email__iexact=value).exists() == False:
        raise ValidationError('Parent Email does not exists.')



class FetchParentForm(forms.ModelForm):
    your_email = forms.CharField(
        widget=forms.EmailInput(
            attrs={"class": "form-control", "placeholder": "Enter your email address"}),
        required=True,
        max_length=75)
    parent_email = forms.CharField(
        widget=forms.EmailInput(
            attrs={"class": "form-control", "placeholder": "Enter parent email address"}),
        required=True,
        max_length=75)

    class Meta:
        model = FetchParentRequest
        fields = ['your_email', 'parent_email']

    def __init__(self, *args, **kwargs):
        super(FetchParentForm, self).__init__(*args, **kwargs)
        self.fields['your_email'].validators.append(UniqueEmailValidator)
        self.fields['your_email'].validators.append(SignupDomainValidator)
        self.fields['parent_email'].validators.append(SignupDomainValidator)
        self.fields['parent_email'].validators.append(ParentEmailValidator)

tdt/emailconfig/views.py
from django.shortcuts import render
from django.views.generic import View
from .forms import FetchParentForm


class FetchParentView(View):
    form_class = FetchParentForm
    template_name = 'fetchparent.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            fetch_request = form.save()
        return render(request, self.template_name, {'form': form})

tdt/emailconfig/templates/fetchparent.html
{% load staticfiles %}
<html>
  <head>
    <title>Fetch Parent</title>
    <!-- Meta-Tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta
      name="keywords"
      content="Existing Login Form Widget Responsive, Login Form Web Template, Flat Pricing Tables, Flat Drop-Downs, Sign-Up Web Templates, Flat Web Templates, Login Sign-up Responsive Web Template, Smartphone Compatible Web Template, Free Web Designs for Nokia, Samsung, LG, Sony Ericsson, Motorola Web Design"
    />
    <script type="application/x-javascript">
      addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);

      function hideURLbar() { window.scrollTo(0, 1); }
    </script>
    <!-- //Meta-Tags -->
    <link
      href="{% static 'css/popuo-box.css' %}"
      rel="stylesheet"
      type="text/css"
      media="all"
    />
    <!-- Style -->
    <link
      rel="stylesheet"
      href="{% static 'css/style.css' %}"
      type="text/css"
      media="all"
    />
    <!-- Fonts -->
    <link
      href="//fonts.googleapis.com/css?family=Quicksand:300,400,500,700"
      rel="stylesheet"
    />
    <!-- //Fonts -->
  </head>

  <body>
    <h1></h1>
    <div class="w3layoutscontaineragileits">
      <h2>Fetch Parent</h2>
      <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <P>
          <label for="{{ form.your_email.id_for_label }}"></label>
          {{ form.your_email.errors }}
          <input
            type="text"
            name="your_email"
            id="id_your_email"
            placeholder="Enter your email address"
          />
        </P>
        <P
          ><label for="{{ form.parent_email.id_for_label }}"></label>
          {{ form.parent_email.errors }}
          <input
            type="text"
            name="parent_email"
            id="id_parent_email"
            placeholder="Enter parent email address"
          />
        </P>
        <center><input type="submit" value="Fetch Parent" /></center>
        <div class="aitssendbuttonw3ls">
          <p>
            To register new account <span>→</span>
            <a href="{% url 'authentication:user_signup' %}"> Click Here</a>
          </p>
        </div>
      </form>
    </div>
    <script
      type="text/javascript"
      src="{% static 'js/jquery-2.1.4.min.js' %}"
    ></script>
    <!-- pop-up-box-js-file -->
    <script
      src="{% static 'js/jquery.magnific-popup.js' %}"
      type="text/javascript"
    ></script>
    <!--//pop-up-box-js-file -->
    <script>
      $(document).ready(function() {
        $(".w3_play_icon,.w3_play_icon1,.w3_play_icon2").magnificPopup({
          type: "inline",
          fixedContentPos: false,
          fixedBgPos: true,
          overflowY: "auto",
          closeBtnInside: true,
          preloader: false,
          midClick: true,
          removalDelay: 300,
          mainClass: "my-mfp-zoom-in"
        });
      });
    </script>
  </body>
</html>