tdt/authentication/urls.py
from django.urls import path,include,re_path
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from authentication import views


app_name = 'authentication'
urlpatterns = [
	# path('signup/',(views.UserSignupForm.as_view()), name='signup'),
	path('admin/signup/',(views.AdminUserSignupForm.as_view()), name='admin_signup'),
	path('user/signup/',(views.NormalUserSignupForm.as_view()), name='user_signup'),
	path('logout/', views.logout_view, name='logout'),
	path('login/', (auth_views.LoginView.as_view(template_name='index.html')), name='login'),
	]

tdt/emailconfig/urls.py
from django.urls import path,include,re_path
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from emailconfig import views


app_name = 'emailconfig'
urlpatterns = [
	path('user/fetch/parent/',(views.FetchParentView.as_view()), name='fetchparent'),
	

	]

tdt/tdt/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('authentication.urls', namespace='authentication')),
    path('', include('emailconfig.urls', namespace='emailconfig')),
    path('product/', include('product.urls', namespace='products')),
    path('order/', include('order.urls', namespace='order')),
    path('', include('dashboard.urls', namespace='dashboard')),

    path('forgot/password/reset/', auth_views.PasswordResetView.as_view(template_name='registration/forgot_password.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='registration/forgot_password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/forgot_password_reset.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name= 'registration/forgot_password_reset_complete.html'), name='password_reset_complete'),
    # path('', include('home.urls', namespace='home')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tdt/authentication/models.py
# users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

import datetime

from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.validators import RegexValidator
from django.db import models
from django.db.models.signals import post_delete
from django.utils.timezone import utc
import random
import string
alphanumeric = RegexValidator(r'^[a-zA-Z]*$', 'Numbers are not allowed.')


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            pass
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)

        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        code = ''.join(random.choices(
            string.ascii_letters + string.digits, k=16))
        extra_fields.setdefault('code', code)
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    GENDER_TYPE = (('Male', 'Male'),
                   ('Female', 'Female'),
                   ('Others', 'Others')
                   )
    first_name = models.CharField(max_length=30, blank=True)
    last_name = models.CharField(max_length=30, blank=True)
    phone = models.CharField(max_length=50)
    email = models.EmailField()
    code = models.CharField(max_length=16, null=False,blank=False,unique=True)
    gender = models.CharField(max_length=250, choices=GENDER_TYPE)
    address = models.CharField(max_length=250)
    image = models.ImageField(null=True, blank=True,
                              upload_to='media/images/user/%Y-%m-%d/')

    objects = UserManager()

    def __str__(self):
        return self.email


class AdminUser(models.Model):
    admin_user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='AdminUser')

    def __str__(self):
        return 'Admin User-{}'.format(self.admin_user.username)


class NormalUser(models.Model):
    user = models.OneToOneField(
        User, on_delete=models.CASCADE, related_name='NormalUser')
    approved = models.BooleanField(default=False)
    parent_user = models.ForeignKey(User,on_delete=models.CASCADE, related_name='Normal_Parent_User',max_length=100)
    parent_code = models.CharField(max_length=16,unique=True,null=False,blank=False)

    def __str__(self):
    	return 'Normal User-{}'.format(self.user.username)

tdt/authentication/views.py
from django.shortcuts import redirect, render
from django.utils.decorators import method_decorator
from django.contrib.auth import logout
from authentication.models import User,AdminUser,NormalUser
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import SignUpForm, AdminSignUpForm,NormalUserSignUpForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AdminPasswordChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib import messages
from django.shortcuts import render, redirect
import random
import string


class UserSignupForm(View):
    form_class = SignUpForm
    template_name = 'signup.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            # cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            code = ''.join(random.choices(
                string.ascii_letters + string.digits, k=16))
            user.code = code
            print(user.code)
            user.save()
            # returns these objects if credential are correct
            user = authenticate(username=username, password=password)
            # if user is not None:
            #     if user.is_active:
            #         login(request, user)
            #         # after signup redirect to profile settings
            #         return redirect('authentication:login')

        return render(request, self.template_name, {'form': form})


class AdminUserSignupForm(View):
    form_class = SignUpForm
    template_name = 'admin_signup.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)

            # cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            code = ''.join(random.choices(string.ascii_letters + string.digits, k=16))
            user.code = code
            user.save()
            admin = AdminUser.objects.create(admin_user=user)
            admin.save()
            # returns these objects if credential are correct
            user = authenticate(username=username, password=password)
            # if user is not None:
            #     if user.is_active:
            #         login(request, user)
            #         # after signup redirect to profile settings
            #         return redirect('authentication:login')
        return render(request, self.template_name, {'form': form})

class NormalUserSignupForm(View):
    form_class = NormalUserSignUpForm
    template_name = 'normal_user_signup.html'

    # display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    # process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():
            user = form.save(commit=False)
            # cleaned (normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            parent_code = form.cleaned_data['parent_code']
            user.set_password(password)
            code = ''.join(random.choices(string.ascii_letters + string.digits, k=16))
            user.code = code
            user.save()
            parent_user = User.objects.get(code = parent_code)
            parent_user_code = parent_user.code
            if parent_user_code==parent_code:
            	normal_user = NormalUser.objects.create(user=user,parent_user=parent_user,parent_code=parent_code)
            	normal_user.save()
            user = authenticate(username=username, password=password)
            # if user is not None:
            #     if user.is_active:
            #         login(request, user) 
            #         # after signup redirect to profile settings
            #         return redirect('authentication:login')
        return render(request, self.template_name, {'form': form})

def logout_view(request):
    logout(request)
    return redirect('authentication:login')

tdt/authentication/templates/admin_signup.html
{% load staticfiles %}
{% load staticfiles %}
<html>

<head>
    <title>Register</title>
    <!-- Meta-Tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="keywords" content="Existing Login Form Widget Responsive, Login Form Web Template, Flat Pricing Tables, Flat Drop-Downs, Sign-Up Web Templates, Flat Web Templates, Login Sign-up Responsive Web Template, Smartphone Compatible Web Template, Free Web Designs for Nokia, Samsung, LG, Sony Ericsson, Motorola Web Design">
    <script type="application/x-javascript">
    addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);

    function hideURLbar() { window.scrollTo(0, 1); }
    </script>
    <!-- //Meta-Tags -->
    <link href="{% static 'css/popuo-box.css' %}" rel="stylesheet" type="text/css" media="all" />
    <!-- Style -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all">
    <!-- Fonts -->
    <link href="//fonts.googleapis.com/css?family=Quicksand:300,400,500,700" rel="stylesheet">
    <!-- //Fonts -->
</head>

<body>
    <h1></h1>
    <div class="w3layoutscontaineragileits">
        <h2>Admin Register</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <input type="text" name="first_name" class="text-info" placeholder=" Enter your first name" maxlength="30" required="" id="id_first_name">
            <input type="text" name="last_name" class="text-info" placeholder=" Enter your last name" maxlength="30" required="" id="id_last_name">
            <input type="text" name="username" class="text-info" placeholder=" Enter your username" maxlength="30" required="" id="id_username"><input type="email" name="email" class="form-control" placeholder="Enter your email address" maxlength="75" required="" id="id_email">
            <input type="password" name="password" class="text-info" placeholder="Enter the password" required="" id="id_password"></p>
            <center><input type="submit" value="Register Now"></center>
        </form>
    </div>
    <script type="text/javascript" src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
    <!-- pop-up-box-js-file -->
    <script src="{% static 'js/jquery.magnific-popup.js' %}" type="text/javascript"></script>
    <!--//pop-up-box-js-file -->
    <script>
    $(document).ready(function() {
        $('.w3_play_icon,.w3_play_icon1,.w3_play_icon2').magnificPopup({
            type: 'inline',
            fixedContentPos: false,
            fixedBgPos: true,
            overflowY: 'auto',
            closeBtnInside: true,
            preloader: false,
            midClick: true,
            removalDelay: 300,
            mainClass: 'my-mfp-zoom-in'
        });
    });
    </script>
</body>

</html>

tdt/authentication/templates/index.html
{% load staticfiles %}
<html>
  <head>
    <title>Login</title>
    <!-- Meta-Tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta
      name="keywords"
      content="Existing Login Form Widget Responsive, Login Form Web Template, Flat Pricing Tables, Flat Drop-Downs, Sign-Up Web Templates, Flat Web Templates, Login Sign-up Responsive Web Template, Smartphone Compatible Web Template, Free Web Designs for Nokia, Samsung, LG, Sony Ericsson, Motorola Web Design"
    />
    <script type="application/x-javascript">
      addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);

      function hideURLbar() { window.scrollTo(0, 1); }
    </script>
    <!-- //Meta-Tags -->
    <link
      href="{% static 'css/popuo-box.css' %}"
      rel="stylesheet"
      type="text/css"
      media="all"
    />
    <!-- Style -->
    <link
      rel="stylesheet"
      href="{% static 'css/style.css' %}"
      type="text/css"
      media="all"
    />
    <!-- Fonts -->
    <link
      href="//fonts.googleapis.com/css?family=Quicksand:300,400,500,700"
      rel="stylesheet"
    />
    <!-- //Fonts -->
  </head>

  <body>
    <h1></h1>
    <div class="w3layoutscontaineragileits">
      <h2>Login here</h2>
      <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <P>
          <label for="{{ form.username.id_for_label }}"></label>
          {{ form.username.errors }}
          <input
            type="text"
            name="username"
            id="id_username"
            placeholder="Username"
          />
        </P>
        <P
          ><label for="{{ form.password.id_for_label }}"></label>
          {{ form.password.errors }}
          <input
            type="password"
            name="password"
            id="id_password"
            placeholder="Password"
          />
        </P>
        <ul class="agileinfotickwthree">
          <li>
            <center>
              <a href="{% url 'password_reset' %}">Forgot password ?</a>
            </center>
          </li>
        </ul>
        <center><input type="submit" value="LOGIN" /></center>
        <div class="aitssendbuttonw3ls">
          <p>
            To register new account <span>→</span>
            <a href="{% url 'authentication:user_signup' %}"> Click Here</a>
          </p>
        </div>
      </form>
    </div>
    <script
      type="text/javascript"
      src="{% static 'js/jquery-2.1.4.min.js' %}"
    ></script>
    <!-- pop-up-box-js-file -->
    <script
      src="{% static 'js/jquery.magnific-popup.js' %}"
      type="text/javascript"
    ></script>
    <!--//pop-up-box-js-file -->
    <script>
      $(document).ready(function() {
        $(".w3_play_icon,.w3_play_icon1,.w3_play_icon2").magnificPopup({
          type: "inline",
          fixedContentPos: false,
          fixedBgPos: true,
          overflowY: "auto",
          closeBtnInside: true,
          preloader: false,
          midClick: true,
          removalDelay: 300,
          mainClass: "my-mfp-zoom-in"
        });
      });
    </script>
  </body>
</html>

tdt/authentication/templates/normal_user_signup.html
{% load staticfiles %} {% load staticfiles %} {% load staticfiles %}
<html>
  <head>
    <title>Register</title>
    <!-- Meta-Tags -->
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta
      name="keywords"
      content="Existing Login Form Widget Responsive, Login Form Web Template, Flat Pricing Tables, Flat Drop-Downs, Sign-Up Web Templates, Flat Web Templates, Login Sign-up Responsive Web Template, Smartphone Compatible Web Template, Free Web Designs for Nokia, Samsung, LG, Sony Ericsson, Motorola Web Design"
    />
    <script type="application/x-javascript">
      addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false);

      function hideURLbar() { window.scrollTo(0, 1); }
    </script>
    <!-- //Meta-Tags -->
    <link
      href="{% static 'css/popuo-box.css' %}"
      rel="stylesheet"
      type="text/css"
      media="all"
    />
    <!-- Style -->
    <link
      rel="stylesheet"
      href="{% static 'css/style.css' %}"
      type="text/css"
      media="all"
    />
    <!-- Fonts -->
    <link
      href="//fonts.googleapis.com/css?family=Quicksand:300,400,500,700"
      rel="stylesheet"
    />
    <!-- //Fonts -->
  </head>

  <body>
    <h1></h1>
    <div class="w3layoutscontaineragileits">
      <h2>User Register</h2>
      <form method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <input
          type="text"
          name="username"
          class="text-info"
          placeholder=" Enter your username"
          maxlength="30"
          required=""
          id="id_username"
        />
        <input
          type="email"
          name="email"
          class="form-control"
          placeholder="Enter your email address"
          maxlength="75"
          required=""
          id="id_email"
        /><input
          type="password"
          name="password"
          class="text-info"
          placeholder="Enter the password"
          required=""
          id="id_password"
        />
        <input
          type="text"
          name="parent_code"
          class="form-control"
          placeholder="Enter your parent_code"
          maxlength="16"
          required=""
          id="id_parent_code"
        />
        <ul class="agileinfotickwthree">
          <li>
            <center>
              <a href="{% url 'emailconfig:fetchparent' %}">Fetch Parent ?</a>
            </center>
          </li>
        </ul>
        <center><input type="submit" value="Register Now" /></center>
        <div class="aitssendbuttonw3ls">
          <p>
            To Login <span>→</span>
            <a href="{% url 'authentication:login' %}"> Click Here</a>
          </p>
        </div>
      </form>
    </div>
    <script
      type="text/javascript"
      src="{% static 'js/jquery-2.1.4.min.js' %}"
    ></script>
    <!-- pop-up-box-js-file -->
    <script
      src="{% static 'js/jquery.magnific-popup.js' %}"
      type="text/javascript"
    ></script>
    <!--//pop-up-box-js-file -->
    <script>
      $(document).ready(function() {
        $(".w3_play_icon,.w3_play_icon1,.w3_play_icon2").magnificPopup({
          type: "inline",
          fixedContentPos: false,
          fixedBgPos: true,
          overflowY: "auto",
          closeBtnInside: true,
          preloader: false,
          midClick: true,
          removalDelay: 300,
          mainClass: "my-mfp-zoom-in"
        });
      });
    </script>
  </body>
</html>

tdt/authentication/templates/signup.html
{% load staticfiles %}
{% block index %}
            <!--************************************
                Inner Page Banner Start
        *************************************-->
        <!--************************************
                Inner Page Banner End
        *************************************-->
        <!--************************************
                Main Start
        *************************************-->
        <main id="tg-main" class="tg-main tg-paddingzero tg-haslayout">
            <!--************************************
                    Login Register Start
            *************************************-->
            <div class="tg-main-section tg-haslayout">
                <div class="container">
                    <div class="row">
                        <div id="tg-content" class="tg-content">
                                <div class="col-xs-12 col-sm-12 col-md-10 col-md-push-1 col-lg-8 col-lg-push-2">
                                    <form method="post">
                                        {% csrf_token %}
                                                {{ form.as_p }}
                                                <div class="form-group">
                                                    <div class="tg-checkbox">
                                                        <input type="checkbox" id="terms">
                                                        <label for="terms">I have read the <a href="#">Terms &amp; Conditions</a> and accept them</label>
                                                    </div>
                                                </div>
                                                <div class="form-group">
                                                    <div class="tg-checkbox">
                                                        <span>Already have an account?<a href="#"> Login Now</a></span>
                                                    </div>
                                                </div>
                                                <button class="tg-btn" type="submit">Register Now</button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!--************************************
                    Login Register End
            *************************************-->
{% endblock %}